# Generated by Django 4.1.6 on 2023-04-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('about', models.TextField(max_length=400)),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
            ],
        ),
        migrations.CreateModel(
            name='talks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('domain', models.CharField(max_length=50)),
                ('slides', models.BooleanField(default=False, verbose_name='Yes')),
                ('duration', models.DurationField()),
                ('availability', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
