# Generated by Django 4.1.6 on 2023-04-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='talks',
        ),
    ]
