# Generated by Django 4.1.6 on 2023-04-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_first_name_profile_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
    ]
