# Generated by Django 4.1.6 on 2023-05-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usermodel_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
