# Generated by Django 5.0 on 2023-12-30 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_rename_firstname_usermodel_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='talks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('domain', models.CharField(max_length=50)),
                ('slides', models.BooleanField(default=False, verbose_name='Yes')),
                ('duration', models.DurationField()),
                ('availability', models.DateField()),
                ('firstname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
